---
# enable (yes) or disable (no) certain software
configure_mac_app_store: yes
configure_python: yes
configure_rstats: yes


# Mac App Store (mas) applications
# NOTE: need to save your password in AppStore for free apps....
mas_installed_apps:
  - { id: 1333542190, name: "1Password" } 
  - { id: 409222199, name: "Cyberduck"}
  - { id: 441258766, name: "Magnet"}
  - { id: 1179623856, name: "Pastebot"}
mas_email: "wcmbishop@gmail.com"
mas_password: ""
