---
# enable (yes) or disable (no) certain software
configure_mac_app_store: no
configure_python: no
configure_rstats: no


# define local download folder
downloads: ~/.ansible-downloads/


# homberew "tap" installation sources
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers


# packages to instsall with Homebrew
# - search for brew packages in the cmd line with: brew search <package-name>
homebrew_installed_packages:
  - git
  - openssl
  - mas
  - readline
  - sqlite
  - wget


# applications to install with Homebrew Cask
# - search for cask applications in the cmd line with: brew search <app-name>
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - db-browser-for-sqlite. # SQLite IDE - https://sqlitebrowser.org
  - docker  # containerization - https://www.docker.com/
  - dropbox  # cloud file system - https://www.dropbox.com/
  - google-chrome  # web-browswer - https://www.google.com/chrome/
  - iterm2  # terminal app - https://www.iterm2.com
  - licecap  # gif screen capture - https://www.cockos.com/licecap/
  - macdown  # markdown text   editor - https://macdown.uranusjr.com
  - sequel-pro  # SQL client - https://www.sequelpro.com/
  - skitch  # image screen capture - https://evernote.com/products/skitch
  - slack   # chat - https://slack.com
  - sourcetree  # Git UI - https://www.sourcetreeapp.com
  - sublime-text  # text editor - https://www.sublimetext.com
  - textexpander  # text snippets - https://textexpander.com
  - vlc  # video player https://www.videolan.org/vlc/index.html


# blank default variables for optional programming languages
rstats:
  homebrew_installed_packages: []
  homebrew_cask_apps: []
python:
  homebrew_installed_packages: []
  homebrew_cask_apps: []


# Mac App Store (mas) applications
# - search for mas apps in the cmd line with: mas search <app-name>
# - NOTE: need to save your password in AppStore for free apps....
mas_installed_apps: [
  # - { id: 1179623856, name: "Pastebot"}  # example
]
mas_email: ""
mas_password: ""
